
services:
  # FastAPI
  app:
    build: .
    container_name: ai-interactive-smart-doll-app
    ports:
      - "8001:8001"
    volumes:
      - ./app:/app/app # Mount the app directory for live reloading
    env_file:
      - ./.env
    depends_on:
      - db
      - qdrant
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]

  # PostgreSQL
  db:
    image: postgres:latest
    container_name: postgres-doll-compose
    volumes:
      - postgres_data_compose:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d # --- ADD THIS LINE ---
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=doll_user
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=doll_db

  #Qdrant
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-doll-compose
    ports:
      - "6333:6333" # API port
      - "6334:6334" # gRPC port
    volumes:
      - qdrant_data_compose:/qdrant/storage

volumes:
  postgres_data_compose:
  qdrant_data_compose:
